name: Build WinSparkle

on:
  repository_dispatch:
    types:
      - webhook-1
      - webhook-2
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build DLL
    runs-on: windows-latest
    strategy:
      matrix:
        platform: [x64]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependency packages
      run: nuget restore

    - name: Build binaries
      run: msbuild -m -t:Build -p:Configuration=Release -p:Platform=${{ matrix.platform }} WinSparkle.sln

    - name: Archive binaries
      uses: actions/upload-artifact@v4
      with:
        name: winsparkle-binaries-${{ matrix.platform }}
        path: |
          include/winsparkle*.h
          **/WinSparkle.dll
          **/WinSparkle.lib
          **/WinSparkle.pdb
          **/example*.exe
          **/winsparkle-tool.exe

  build-nuget:
    name: Build NuGet package
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4



      - name: Fetch binaries (x64)
        uses: actions/download-artifact@v4
        with:
          name: winsparkle-binaries-x64



      - name: Build NuGet package
        run: nuget pack nuget/WinSparkle.nuspec -Verbosity detailed

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: "*.nupkg"

  publish-nuget:
    name: Publish NuGet
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    needs: build-nuget
    steps:
      - name: Fetch artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package

      - uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NUGET_API_KEY }}
          nuget-api-key-source: https://www.nuget.org/api/v2/package

      - name: Publish to NuGet
        run: nuget push *.nupkg -Source https://www.nuget.org/api/v2/package

  publish-release:
    name: Publish release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build-nuget
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

  

      - name: Fetch binaries (x64)
        uses: actions/download-artifact@v4
        with:
          name: winsparkle-binaries-x64

 

      - name: Package tarballs
        run: make -f distrib.makefile

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          prerelease: true
          artifacts: "WinSparkle*.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
